"""empty message

Revision ID: 119310dc165e
Revises: 338b6956277c
Create Date: 2023-03-30 08:10:22.474635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119310dc165e'
down_revision = '338b6956277c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
